server:
  port: 8080

# Halkyon properties to configure the component, link or capability
dekorate:
  component:
    name: fruit-backend-sb
    deploymentMode: dev
    exposeService: true
  link:
    name: link-to-database
    componentName: fruit-backend-sb
    type: Secret
    ref: postgres-db-config
  capability:
    name: postgres-db
    category: database
    type: postgres
    version: "10.6"
    parameters:
      - name: DB_CONFIG_NAME
        value: postgres-db-config
      - name: DB_USER
        value: admin
      - name: DB_PASSWORD
        value: admin
      - name: DB_NAME
        value: sample-db

spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
