apiVersion: apps/v1
kind: Deployment
metadata:
  name: halkyon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: halkyon-operator
  template:
    metadata:
      labels:
        name: halkyon-operator
    spec:
      serviceAccountName: halkyon-operator
      containers:
        - name: halkyon-operator
          image: quay.io/halkyonio/operator:v0.1.2
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - halkyon-operator
          args:
            - --zap-encoder
            - $(ZAP_ENCODER)
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "halkyon-operator"
            - name: ZAP_ENCODER
              value: "console"
            # - name: BASE_S2I_IMAGE
            #   value: "quay.io/halkyonio/spring-boot-maven-s2i"
            # - name: REGISTRY_ADDRESS
            #   value: "docker-registry.default.svc:5000"